title: Linda Vuong
logo: /front_geisel.jpg
description: Contact me at lhvuong1124@gmail.com [GitHub](https://github.com/lhvuong11), [Resume](https://drive.google.com/file/d/1I-BmKFtA3IP3xDzzOO0B2_PnVqz4zsBJ/view?usp=sharing)
show_downloads: false
theme: jekyll-theme-minimal
