title: Linda Vuong
logo: /front_geisel.jpg
description: Contact: [lhvuong1124@gmail.com](https://mail.google.com/mail/u/0/?ogbl#inbox?compose=CllgCKHWNbWlnFbxVZBrwztrrsmKlWCnCszzhGzJKXjVqtcWZtDBBJgQbNlfsHghxCbnFBTmvFg)
show_downloads: false
theme: jekyll-theme-minimal
